criticalities = {
    "Unexpected System Shutdown": 0.9,
    "System Inoperable": 0.9,
    "Loose Connection": 0.4,
    "Display Flickering": 0.3,
    "Poor Battery Life": 0.6,
    "Slow Boot Time": 0.5,
    "Unstable Wi-Fi Connection": 0.4,
    "Overheating": 0.7,
    "Excessive Fan Noise": 0.2,
    "Faulty Keyboard": 0.5,
    "Unreliable Touchpad": 0.4,
    "Audio Distortion": 0.3,
    "Non-functional USB Port": 0.5,
    "GPU Crashing": 0.8,
    "Firmware Update Issue": 0.6,
    "Defective Power Button": 0.7,
    "Loose Charging Port": 0.4,
    "Faulty Charging": 0.7,
    "Unstable Bluetooth Connection": 0.4,
    "System Freezing": 0.8,
    "Low Webcam Quality": 0.3,
    "Stiff Hinge": 0.3,
    "Excessive Weight": 0.2,
    "Poor Screen Visibility": 0.3,
    "Poor Display Color": 0.2,
    "Low Speaker Volume": 0.2,
    "Unexpected System Reboot": 0.8,
    "Ink Cartridge Recognition Issue": 0.6,
    "Sleep Mode Wake Issue": 0.5,
    "Hard Drive Clicking Noise": 0.7,
    "Monitor Power Issue": 0.9,
}