name: Docker image builds
on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  server:
    uses: ./.github/workflows/docker-build.yml
    permissions:
      packages: write
    with:
      name: "server"
      username: "6monthslater"
      folder: "server"
    secrets:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  scraper:
    uses: ./.github/workflows/docker-build.yml
    permissions:
      packages: write
    with:
      name: "scraper"
      username: "6monthslater"
      target: "scraper"
      folder: "scraper"
    secrets:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  analyzer:
    uses: ./.github/workflows/docker-build.yml
    permissions:
      packages: write
    with:
      name: "analyzer"
      username: "6monthslater"
      target: "analyzer"
      folder: "scraper"
    secrets:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  crawler:
    uses: ./.github/workflows/docker-build.yml
    permissions:
      packages: write
    with:
      name: "crawler"
      username: "6monthslater"
      target: "crawler"
      folder: "scraper"
    secrets:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}