name: Linting

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  lint:
    name: Run tests for scraper with pytest
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: "3.10"
      - name: "Install deps"
        run: sudo apt-get update; sudo apt-get install libcurl4-openssl-dev libssl-dev maven;
      - run: pip install -r requirements.txt
        working-directory: ./scraper
      - run: python -m textblob.download_corpora
        working-directory: ./scraper
      - run: setup.sh
        working-directory: ./scraper
      - name: Run Tests
        working-directory: ./scraper
        timeout-minutes: 5
        run: pytest
        env:
          AMAZON_COOKIE: ${{ secrets.AMAZON_COOKIE }}
